### ISSUE TITLE
General env var question

### ISSUE THREAD

**Issue by cpoole** [katosys/portus#19]
Is there a specific reason you chose to individually SED the env vars into the conf files?

I feel like the startup scripts would be easier to maintain if you used a tool like envsubts 
https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html

genuinely curious, I don't have a major preference either way.

**Comment by h0tbird** [comment]
No specific reason, it was the first thing that occurred to me. I will have a look at `envsubst`, thank you for the info.

**Comment by cpoole** [comment]
Sure thing, let me know if you're interested in trying it out and I can submit a PR. If not just go ahead and close this issue

**Comment by cpoole** [comment]
friendly bump

**Comment by MatthewHartstonge** [comment]
Yeeeeeaaaahhh.. Maybe just check if not null?
I just ran into an issue where I'm deploying a `config-local.yml file` but due to the init script setting the ENVVARs if null, the ENVVARs take precedence over my `config-local.yml` file.

**Comment by h0tbird** [comment]
@cpoole I will stick to `sed` over `envsubst`. I think it also aligns better with the issue reported by @MatthewHartstonge which I think might be addressed by https://github.com/katosys/portus/commit/2ee0584042b2304d3c9dff312bc99a2f384efcb0. Let me know if you test it.

**Comment by cpoole** [comment]
@h0tbird agreed, in the past 5 months docker has really switched to adopt the secrets file, making this a moot point
